Add simple datastreams tx/rx example
astarte-platform/astarte-device-sdk-python pull request #103
Opened 2023-07-21 14:23 UTC by sorru94

2023-07-26 13:20 UTC, joshuachp approved these changes

2023-07-26 14:26 UTC, harlem88 requested changes

2023-07-26 14:26 UTC, harlem88 commented on examples/datastreams/main.py
> +""" Unset property example
```suggestion
""" Individual datastream example
```

2023-07-26 14:26 UTC, harlem88 commented on examples/datastreams/main.py
> +Example showing how to set and unset a property.
```suggestion
Example showing how to send/receive individual datastreams.
```

2023-07-26 16:09 UTC, lucaato approved these changes

2023-07-27 09:34 UTC, harlem88 approved these changes

2023-07-27 10:54 UTC, merged