Add Example
astarte-platform/astarte-device-sdk-python pull request #18
Opened 2022-02-10 17:16 UTC by FrancescoVaiani

Add a Generic sensor example where random values are sent every 5 seconds.

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2022-02-14 16:06 UTC, bettio requested changes
Let's use the 1.0 for all the interfaces.

2022-02-14 16:06 UTC, bettio commented on examples/example_device/interfaces/org.astarte-platform.genericsensors.Values.json
> +    "version_minor": 1,
let's use: https://raw.githubusercontent.com/astarte-platform/astarte/release-1.0/standard-interfaces/org.astarte-platform.genericsensors.Values.json

2022-02-14 16:17 UTC, bettio requested changes

2022-02-14 16:17 UTC, bettio commented on examples/example_device/config.ini
> +pairing_base_url =
Let's use same schema of `astarte-transport.conf` from `stream-qt5-test`: 
```ini
[AstarteTransport]
pairingJwt=PAIRING_JWT_HERE
pairingUrl=https://PAIRING_URL_HERE
realm=REALM_HERE
persistencyDir=PERSISTENCY_DIR_HERE
```

2022-02-14 16:17 UTC, bettio commented on examples/event_listener/config.ini
> +pairing_base_url =
Same here:
```ini
[AstarteTransport]
pairingJwt=PAIRING_JWT_HERE
pairingUrl=https://PAIRING_URL_HERE
realm=REALM_HERE
persistencyDir=PERSISTENCY_DIR_HERE
```

2022-04-14 14:17 UTC, davidebriani commented on examples/event_listener/event_listener.py
> +_INTERFACES_DIR = os.path.join(Path(__file__).parent.absolute(), 'interfaces')
Or, slightly more readable:
```python
_INTERFACES_DIR = os.path.join(_ROOT_DIR, 'interfaces')
```

2022-04-14 14:17 UTC, davidebriani commented on examples/event_listener/event_listener.py
> +    pairing_url = _PAIRING_URL
Just pass the original variables to initialize the device, these assignments feel superfluous and do not add value or readability to the example

2022-04-14 14:26 UTC, davidebriani approved these changes

2022-04-15 13:03 UTC, harlem88 requested changes

2022-04-15 13:03 UTC, harlem88 commented on examples/event_listener/README.md
> +This is an example usage of Device connection  publication of values on either
Remove double space between `connection` and `publication`.

2022-04-15 13:03 UTC, harlem88 commented on examples/example_device/README.md
> +This is an example usage of Device connection  publication of values on either
same here.

2022-04-15 13:40 UTC, harlem88 approved these changes

2022-04-15 14:34 UTC, davidebriani commented on examples/event_listener/README.md
> +Datastream and Properties interfaces.
Title and abstract do not reflect the purpose of the example. You could say something like:
> This is an example of how to use the Device SDK to connect a device to Astarte and handle incoming messages sent to the device by third parties.

2022-04-15 14:34 UTC, davidebriani commented on examples/example_device/README.md
> +Datastream and Properties interfaces.
Maybe not a clear sentence, there might be a word missing.
How about:
> This is an example of how to use the Device SDK to connect a device to Astarte and send data on `datastream` or `properties` interfaces.

2022-04-15 14:49 UTC, davidebriani approved these changes

2023-02-10 15:36 UTC, sorru94 commented on examples/event_listener/README.md
> +the start of `example_device.py`
```suggestion
the start of `event_listener.py`
```

2023-02-10 15:54 UTC, sorru94 commented on examples/example_device/example_device.py
> +        device.send("org.astarte-platform.genericsensors.Values", f"/{sensor_id}/value", temp, datetime.now())
```suggestion
        device.send("org.astarte-platform.genericsensors.Values", f"/{sensor_id}/value", temp, datetime.now(tz=timezone.utc))
```

2023-02-10 15:55 UTC, sorru94 commented on examples/example_device/example_device.py
> +        device.send("org.astarte-platform.genericsensors.Values", f"/{sensor_id}/value", temp, datetime.now())
This removes the warning regarding the timezone that would otherwise appear when running the example.

2023-02-13 09:00 UTC, sorru94 commented
When running one of the examples, the device writes the certificate and key in a folder that is versioned.
I would suggest creating dedicated `persistency_dir` for each example and then gitignoring such directory.

2023-02-13 14:50 UTC, sorru94 commented
In addition, I see the examples are limited to individual datastreams. Could you add also an example for an aggregated object datastream?

2023-02-17 16:01 UTC, sorru94 reviewed
One last suggestion.
In the `event_listener` example it could be helpful to indicate that the `callback` function runs on a separate thread compared to the `main` function.
This could be important when wanting to share data between the two threads and performing non-atomic operations on this data.
As an example [here](https://github.com/sorru94/astarte-device-sdk-python/blob/a98b73df2447cb62e842f135c0867a0633941064/e2etest/main.py#L53-L56) a link to the `e2etests` where this is used.

2023-02-20 11:11 UTC, sorru94 approved these changes

2023-02-20 14:54 UTC, closed without merging