Push get started on sdk-docs
astarte-platform/astarte-device-sdk-python pull request #186
Opened 2024-08-13 15:01 UTC by sorru94

2024-08-14 10:52 UTC, sorru94 commented on .github/workflows/doc-workflow.yaml
> +        if: steps.commit-changes.conclusion == 'success'
Yes, it's about the second point. The previous step could be skipped and we don't want to run this one if the previous one was not.

2024-08-14 12:42 UTC, lucaato approved these changes

2024-08-19 12:48 UTC, harlem88 requested changes

2024-08-20 07:23 UTC, sorru94 commented on .github/workflows/doc-workflow.yaml
> +          echo "Latest release: $latest_release"
Yes, it's there mostly for debugging. But I already checked the workflow so it should be fine.

2024-08-21 07:57 UTC, harlem88 approved these changes

2024-08-22 15:58 UTC, harlem88 approved these changes

2024-08-22 16:05 UTC, merged